name: example
description: Example for ars_dialog
version: 1.0.0+1
homepage: https://github.com/arsamme
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ars_dialog:
    path: ".."

flutter:
  uses-material-design: true
