name: ars_dialog
description: Dialog material widget with blur background and popup animation
version: 1.0.8
homepage: https://github.com/arsamme/flutter-dialogs

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
